os: windows
language: shell

before_install:
  - choco install python --version=3.8
  - python -m pip install --upgrade pip
env: PATH=/c/Python38:/c/Python38/Scripts:$PATH

install:
  - pip install -r requirements.txt

script:
  - pyinstaller "nowplaying.spec"

before_deploy:
  - 7z a ${PROJECT_NAME}-${TRAVIS_TAG}-${TARGET}.zip -r ./dist/*

deploy:
  provider: releases
  api_key: $RELEASE_TOKEN
  file_glob: true
  file: ${PROJECT_NAME}-${TRAVIS_TAG}-${TARGET}.zip
  draft: true
  on:
    tags: true
  name: $TRAVIS_TAG